### ISSUE TITLE
How to convert json into form ?

### ISSUE THREAD

**Issue by Ani-Soft** [danharrin/form-builder#1]
Hi @danharrin ,

Just want to know how can i use saved form json again on form builder page so that i can edit form fields in previous saved form.

TIA

**Comment by danharrin** [comment]
You can use `$this->form->fill()` to fill it back in. Please read the form builder docs.

**Comment by Ani-Soft** [comment]
$this->form->fill() is to fill fields data only i guess.

What i meant was how can i re-edit form fields?
Example:
I generated a dynamic form with two fields "User name" and  "User email" and saved.
later how can i add one more field to it ?
How can i edit form structure again after save?

Please help

**Comment by danharrin** [comment]
You fill the data and then save it back to the same Eloquent model when you're done. This repository is only a small demo of what you can do. If you want to learn about Eloquent, I suggest the Laravel Bootcamp.
